name = "nextjs-ecommerce-poc"
account_id = "70468d7c6f13b6b2ac4e1d2e248690ca"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
NEXT_PUBLIC_API_BASE_URL = "https://api.trulyfreehome.dev"

[env.preview]
NEXT_PUBLIC_API_BASE_URL = "https://api.trulyfreehome.dev"